export enum ActivityType {
  //all activity user can do it
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  BOOKING_TOOL = 'BOOKING_TOOL',

  //only admin can do it
  RESTORE_ACCOUNT = 'RESTORE_ACCOUNT',
  DELETE_ACCOUNT_PERMANENTLY = 'DELETE_ACCOUNT_PERMANENTLY',
  BAN_USER = 'BAN_USER',
  UNBAN_USER = 'UNBAN_USER',
}
